### ISSUE TITLE
Issues with Joe's CV

### ISSUE THREAD

**Issue by TimBennett42** [BENNT3/CV-workshop#1]
# Here is a list of things that need to be edited in Joseph Bloggs' CV.
* Needs a professional email adress.
* Wall of text introduction needs to be shortened and be easier to read.
* Skill list is too long not detailed.
* Use of "maths" in a professional setting.
* General unprofessional writing.
* No clear difference between headings 1 and 2.
* The lack of spellchecking.
* Obvious family member personal reference.
* Unnessesary font size. Document should and easily can be reduced to one page.

**Comment by eallenOP** [comment]
Generally you should have one new issue for each of the things on your list. That way, if you're collaborating with people, you can contain conversations about that one issue in a single thread and keep things nice and organised.
